#!usr/bin/env python3
import re
from datetime import datetime
from datetime import timedelta
invalid = 0; valid = 0
words=["failed password"]
pokusy_ip = {}; pokusy_user = {}; datetimes_ip = {}
pattern_invalid=r"Failed password for invalid user (\w+) from (\S+) port (\d+)"; pattern_valid=r"Failed password for (\w+) from (\S+) port (\d+)"
def check_times_ip(times):
    window = timedelta(minutes=5)
    limit=3
    count=0
    
    print(times)
    print(window)
    #latest = times[0]
    #start= latest - window
    #print(latest)
    #print(start)
    #for t in times:
    #    if t >= start:
    #        count += 1
    #print(count)

with open("./test_log.txt","r") as file:
    for line in file:
        if "]:" not in line:
            continue
        else:
            hlavicka, sprava = line.split("]:",1)
            if any(word in sprava.lower() for word in words):
                month, day, time, hostname, process = hlavicka.split()
                if "invalid user" in sprava.lower():
                    type = "invalid"
                else:
                    type = "valid"
                if type == "valid":
                    match = re.search(pattern_valid, sprava)
                elif type == "invalid":
                    match = re.search(pattern_invalid,sprava)

                if match:
                    ip = match.group(2); user = match.group(1); port=match.group(3)
                    if ip not in pokusy_ip:
                        pokusy_ip[ip] = 1
                    else:
                        pokusy_ip[ip] += 1
                    if user not in pokusy_user:
                        pokusy_user[user] = 1
                    else:
                        pokusy_user[user] += 1
                    timestamp = datetime.strptime(f"{datetime.now().year} {month} {day} {time}","%Y %b %d %H:%M:%S")
                    if ip not in datetimes_ip:
                        datetimes_ip[ip] = [timestamp]
                    else:
                        datetimes_ip[ip].append(timestamp)
                    print(f"[FAILED][{type.upper()}] {month} {day} {time} - user: {user}, ip: {ip}:{port}")
                else:
                    print("match was not found")
                    continue
                if type == "valid":
                    valid += 1
                else:
                    invalid += 1
                print(datetimes_ip[ip])
                check_times_ip(datetimes_ip[ip].sort())
    print(valid, "VALID")
    print(invalid, "INVALID")
    #print(datetimes_ip)
